import { CheckCircle, Star } from "lucide-react";

const reasons = [
  {
    title: "Human-First Approach",
    description: "Every match is personally curated by our experienced team, not generated by algorithms.",
  },
  {
    title: "Exclusive Network",
    description: "Access to a carefully vetted community of exceptional individuals seeking meaningful relationships.",
  },
  {
    title: "Proven Success",
    description: "Over 85% of our clients form lasting relationships within their first year with us.",
  },
  {
    title: "Personalized Service",
    description: "Dedicated relationship coaching tailored to your unique goals and preferences.",
  },
  {
    title: "Complete Privacy",
    description: "Your journey remains confidential with our discreet, professional service.",
  },
  {
    title: "Quality Over Quantity",
    description: "Fewer, better matches mean more meaningful connections and less time wasted.",
  },
];

const testimonials = [
  {
    quote: "After years of disappointing dating apps, Evermore helped me find my person. The personal touch and genuine care made all the difference.",
    author: "Sarah M.",
    role: "Marketing Director",
  },
  {
    quote: "The relationship coaching didn't just help me find love—it helped me become a better partner. Forever grateful for this journey.",
    author: "James T.",
    role: "Entrepreneur",
  },
  {
    quote: "Professional, discreet, and incredibly effective. Evermore understands what it means to find a true life partner.",
    author: "Rebecca L.",
    role: "Attorney",
  },
];

const WhyChooseUs = () => {
  return (
    <section className="py-20 bg-background">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Why Choose Us */}
        <div className="text-center mb-16">
          <h2 className="font-heading text-3xl md:text-5xl font-bold text-foreground mb-6">
            Why Choose Evermore?
          </h2>
          <p className="font-body text-lg md:text-xl text-muted-foreground max-w-3xl mx-auto">
            We're not just another matchmaking service. We're your partners in finding lasting love.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mb-20">
          {reasons.map((reason, index) => (
            <div key={index} className="flex items-start space-x-4 p-6 rounded-lg hover:bg-muted/50 transition-smooth">
              <CheckCircle className="h-6 w-6 text-accent flex-shrink-0 mt-1" />
              <div>
                <h3 className="font-heading text-lg font-semibold text-foreground mb-2">
                  {reason.title}
                </h3>
                <p className="font-body text-muted-foreground leading-relaxed">
                  {reason.description}
                </p>
              </div>
            </div>
          ))}
        </div>

        {/* Testimonials */}
        <div className="bg-muted/30 rounded-2xl p-8 md:p-12">
          <div className="text-center mb-12">
            <h2 className="font-heading text-3xl md:text-4xl font-bold text-foreground mb-4">
              Love Stories We've Helped Create
            </h2>
            <p className="font-body text-muted-foreground">
              Real experiences from real people who found their person.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {testimonials.map((testimonial, index) => (
              <div key={index} className="bg-background rounded-lg p-6 shadow-soft">
                <div className="flex items-center mb-4">
                  {[...Array(5)].map((_, i) => (
                    <Star key={i} className="h-4 w-4 text-accent fill-current" />
                  ))}
                </div>
                <blockquote className="font-body text-foreground mb-4 italic">
                  "{testimonial.quote}"
                </blockquote>
                <div>
                  <cite className="font-body font-semibold text-primary">
                    {testimonial.author}
                  </cite>
                  <p className="font-body text-sm text-muted-foreground">
                    {testimonial.role}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};

export default WhyChooseUs;