"use client";

import { CheckCircle, Star, Heart } from "lucide-react";

const reasons = [
  {
    title: "Human-First Approach",
    description:
      "Every match is personally curated by our experienced team, not generated by algorithms.",
  },
  {
    title: "Exclusive Network",
    description:
      "Access to a carefully vetted community of exceptional individuals seeking meaningful relationships.",
  },
  {
    title: "Proven Success",
    description:
      "Over 85% of our clients form lasting relationships within their first year with us.",
  },
  {
    title: "Personalized Service",
    description:
      "Dedicated relationship coaching tailored to your unique goals and preferences.",
  },
  {
    title: "Complete Privacy",
    description:
      "Your journey remains confidential with our discreet, professional service.",
  },
  {
    title: "Quality Over Quantity",
    description:
      "Fewer, better matches mean more meaningful connections and less time wasted.",
  },
];

const testimonials = [
  {
    quote:
      "After years of disappointing dating apps, Petal & Promise helped me find my person. The personal touch and genuine care made all the difference.",
    author: "Anubhav Singh",
    role: "Bangalore",
  },
  {
    quote:
      "The relationship coaching didn't just help me find love — it helped me become a better partner. Forever grateful for this journey.",
    author: "Siddhi Goel",
    role: "Noida",
  },
  {
    quote:
      "Professional, discreet, and incredibly effective. Petal & Promise understands what it means to find a true life partner.",
    author: "Himanshi Kaushik",
    role: "Gurgaon",
  },
];

const WhyChooseUs = () => {
  return (
    <section className="relative py-28 bg-gradient-to-b from-background via-muted/30 to-background">
      {/* Subtle accent aura */}
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,hsl(var(--accent)/0.08),transparent_70%)] pointer-events-none" />

      <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center mb-20">
          <h2 className="font-heading text-4xl md:text-5xl font-extrabold text-foreground mb-6">
            Why Choose <span className="text-primary">Petal & Promise</span>?
          </h2>
          <p className="font-body text-lg md:text-xl text-muted-foreground max-w-3xl mx-auto leading-relaxed">
            More than matchmaking — we are your{" "}
            <span className="text-accent font-medium">partners in love</span>,
            building meaningful and lasting connections.
          </p>
        </div>

        {/* Reasons Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10 mb-28">
          {reasons.map((reason, index) => (
            <div
              key={index}
              className="group relative p-8 rounded-2xl bg-card/80 backdrop-blur-sm border border-border/50 shadow-sm hover:shadow-luxury transition-all duration-500 hover:-translate-y-1"
              style={{ animationDelay: `${index * 150}ms` }}
            >
              {/* Decorative glow */}
              <div className="absolute inset-0 rounded-2xl bg-gradient-to-br from-accent/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />

              <div className="relative flex items-start space-x-4">
                <CheckCircle className="h-8 w-8 text-accent flex-shrink-0 mt-1 transition-transform group-hover:scale-110" />
                <div>
                  <h3 className="font-heading text-xl font-semibold text-foreground mb-2">
                    {reason.title}
                  </h3>
                  <p className="font-body text-muted-foreground leading-relaxed text-sm">
                    {reason.description}
                  </p>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Divider with accent heart */}
        <div className="flex justify-center mb-16">
          <div className="flex items-center space-x-3 text-accent">
            <span className="h-px w-20 bg-accent/30" />
            <Heart className="h-7 w-7 animate-pulse" />
            <span className="h-px w-20 bg-accent/30" />
          </div>
        </div>

        {/* Testimonials */}
        <div className="bg-gradient-to-br from-muted/40 to-muted/20 rounded-3xl p-10 md:p-16 shadow-inner">
          <div className="text-center mb-14">
            <h2 className="font-heading text-3xl md:text-4xl font-bold text-foreground mb-4">
              Love Stories We’ve Helped Create
            </h2>
            <p className="font-body text-lg text-muted-foreground">
              Real experiences from people who found their forever with{" "}
              <span className="text-primary font-medium">Petal & Promise</span>.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
            {testimonials.map((testimonial, index) => (
              <div
                key={index}
                className="bg-card/90 backdrop-blur-sm rounded-2xl p-8 shadow-soft hover:shadow-luxury hover:-translate-y-1 transition-all duration-500"
              >
                <div className="flex items-center mb-5">
                  {[...Array(5)].map((_, i) => (
                    <Star
                      key={i}
                      className="h-5 w-5 text-accent fill-current"
                    />
                  ))}
                </div>
                <blockquote className="font-body text-foreground mb-6 italic leading-relaxed">
                  “{testimonial.quote}”
                </blockquote>
                <div>
                  <cite className="block font-heading font-semibold text-primary">
                    {testimonial.author}
                  </cite>
                  <p className="font-body text-sm text-muted-foreground">
                    {testimonial.role}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};

export default WhyChooseUs;
